### PR TITLE
Throw an exception if encryption fails

### PR DESCRIPTION
**Pull request by blag**
Closes #28.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Seems like overkill adding a module for an empty class. How about having it alongside where it's used?

**Comment by blag** [comment]
Working on it.

**Comment by blag** [comment]
Fixed.

**Comment by blag** [comment]
Er...no I didn't one sec!

**Comment by blag** [comment]
Fixed.

**Comment by stephenmcd** [comment]
Awesome, thanks for taking on all the feedback :-)

**Comment by blag** [comment]
No worries, thanks for giving the feedback.

I'm working on an encrypting mail backend - is that something you'd like to have?

**Pull request merged**
