### PR TITLE
Flexible body html type

### PR DESCRIPTION
**Pull request by adibo**
A new keyword argument is introduced (body_html_type) to allow for setting mimetype in send_mail and send_mail_template() functions. It defaults to 'text/html', just as it was in the original code.

The change allows to e.g. correctly open encrypted emails in gmail with mailvelope. Such scenario requires to set body_html_type to 'application/pgp-encrypted' or 'text/plain'. Without it, using the default value, opening an email results in "Error! Could not read this encrypted message: Error: Unknown ASCII armor type" for the scenario.

The change is supposed to be neutral and extends the basic use and api. Thus, I hope it can be merged. Thanks in advance!

Adrian

### CODE REVIEW

**Comment by adibo** [comment]
Hi Stephen,
Any chance to see this PR merged? It's been some time now so I wonder what's the plan. I'm still experiencing the same issue (now with the newer mailvelope version 1.5.1). I'm looking forward to hearing from you.

**Comment by stephenmcd** [comment]
Isn't this value something that could be calculated at send time based on whether the email is being encrypted or not?

**Comment by adibo** [comment]
Thanks for a swift response. I'll have a look and come back to you.

**Comment by adibo** [comment]
OK, I've updated the master to have the mimetype set at send time as you suggested. 
Let me know what you think.

**Comment by adibo** [comment]
Now with conflict resolved and added info on EMAIL_EXTRAS_GNUPG_ENCODING in README.rst

**Comment by stephenmcd** [comment]
Thanks!

**Comment by stephenmcd** [comment]
You should add your name to AUTHORS too.

**Comment by adibo** [comment]
Thanks for the merge! My name was already added in the previous PR - thanks.

**Comment by stephenmcd** [comment]
Cool :-)

**Pull request merged**
