### PR TITLE
Fully mimic the signature of django.core.mail.send_mail

### PR DESCRIPTION
**Pull request by blag**
The current signature of `email_extras.utils.send_mail`:

```python
def send_mail(subject, body_text, addr_from, addr_to, fail_silently=False,
              attachments=None, body_html=None, connection=None, headers=None):
```
is supposed to mimic the signature of `django.core.mail.send_mail`:

```python
def send_mail(subject, message, from_email, recipient_list,
              fail_silently=False, auth_user=None, auth_password=None,
              connection=None, html_message=None):
```

but it doesn't quite manage it.

This ensures that our `send_mail` function completely mimics Django's `send_mail` function.

Changes:

* The `body_html` option should be renamed to `html_message`, but to ensure backwards compatibility I kept them both and made sure users only specified [one of them](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR41), and threw a warning if [`body_html` was used](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR46).
* The [`addr_to` argument was renamed to `recipient_list`](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR121). This is more of a cosmetic change than anything else, but it should reduce the cognitive burden for anybody comparing the source code for each function.
* Used Python's `dict()` constructor and Django's `values_list()` to create the dictionary of (address, use_asc) pairs [without explicit loops](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR63) (read: more Pythonic).
* The `auth_user` and `auth_password` options were added, and [used if the `connection` option was `None`](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR56). This is exactly [how Django's `send_mail` function uses them](https://github.com/django/django/blob/master/django/core/mail/__init__.py#L51).
* Updated `send_mail_template` to [use the new argument/option names](https://github.com/stephenmcd/django-email-extras/pull/33/files#diff-cadbcdca5fa0f9090b9471474c099c0dR137).

### CODE REVIEW

**Comment by stephenmcd** [comment]
Is this backward compatible? Can you keep lines under 80 chars?

Thanks for your help.

**Comment by blag** [comment]
It should be completely backwards compatible, but it does throw up a warning if the `body_html` option is specified instead of the `html_message` option.

The previous function didn't accept an `html_message` option - it called that option `body_html`. So it's impossible that current users are specifying both. Because of that, it errors out if users try to pass in both `body_html` and `html_message`. That means it's backwards compatible, but the function now refuses to guess in the face of ambiguity.

And yes I can reformat it to < 80 chars. One sec.

**Comment by stephenmcd** [comment]
Makes sense, thanks a lot!

**Comment by blag** [comment]
I fixed the line length to be < 80 chars. This is now ready to merge.

**Comment by stephenmcd** [comment]
Thanks again

**Pull request merged**
