### PR TITLE
FK relation between Keys and Addresses

### PR DESCRIPTION
**Pull request by GeoTob**
Finally had some time, proposed solution for issue #26

### CODE REVIEW

**Comment by stephenmcd** [comment]
Cool! 

What about a data migration that handles upgrading?

**Comment by GeoTob** [comment]
Yes, once I have a little more time ;-)

**Comment by stephenmcd** [comment]
Cool, I'll wait to merge until then. 

I guess it will actually require splitting the schema migrations into two, so that we can 

1) add new field
2) migrate data
3) drop old field

**Comment by GeoTob** [comment]
that sounds sensible, yup

**Comment by GeoTob** [comment]
had to insert a migration to add a default to `Key.addresses` so we can revert changes

**Comment by stephenmcd** [comment]
Looks good, thanks again!

**Pull request merged**
